package sentencecipher

// Word lists with 256 words each - Theme: Office/Workplace stories
// Each word list has 256 entries (0-255) to encode 1 full byte per word

// 256 employee names (subjects and indirect objects) - 32 rows x 8 columns = 256
var defaultNames = []string{
	"adam", "alex", "alice", "amanda", "amy", "andrew", "angela", "anna",
	"anthony", "ashley", "austin", "barbara", "benjamin", "beth", "blake", "brandon",
	"brian", "brittany", "bruce", "carl", "carlos", "carol", "catherine", "charles",
	"charlotte", "chelsea", "chris", "christina", "claire", "cody", "colin", "connor",
	"cynthia", "daniel", "david", "deborah", "dennis", "diana", "diego", "dominic",
	"donna", "dorothy", "douglas", "dylan", "edward", "elena", "elizabeth", "emily",
	"emma", "eric", "ethan", "eva", "evan", "faith", "felix", "fiona",
	"francis", "frank", "gabriel", "gary", "george", "gloria", "grace", "gregory",
	"hannah", "harold", "harry", "heather", "helen", "henry", "holly", "howard",
	"ian", "irene", "iris", "isaac", "isabella", "ivan", "jack", "jacob",
	"james", "jane", "janet", "jasmine", "jason", "jean", "jeffrey", "jennifer",
	"jeremy", "jessica", "joan", "john", "jonathan", "jordan", "joseph", "joshua",
	"julia", "julie", "justin", "karen", "kate", "katherine", "keith", "kelly",
	"kenneth", "kevin", "kim", "kyle", "laura", "lauren", "lawrence", "leo",
	"leslie", "lily", "linda", "lisa", "logan", "louis", "lucas", "lucy",
	"luke", "lynn", "madison", "margaret", "maria", "marie", "mark", "martha",
	"martin", "mary", "mason", "matthew", "megan", "melissa", "michael", "michelle",
	"mike", "miranda", "molly", "monica", "nancy", "natalie", "nathan", "nicholas",
	"nicole", "nina", "noah", "nora", "oliver", "olivia", "oscar", "owen",
	"pamela", "patricia", "patrick", "paul", "paula", "peter", "philip", "rachel",
	"ralph", "raymond", "rebecca", "richard", "robert", "roger", "ronald", "rose",
	"ruby", "russell", "ruth", "ryan", "samantha", "samuel", "sandra", "sara",
	"sarah", "scott", "sean", "sharon", "shawn", "shirley", "simon", "sophia",
	"spencer", "stephanie", "stephen", "steven", "susan", "teresa", "thomas", "timothy",
	"tina", "todd", "tom", "tony", "tracy", "travis", "tyler", "vanessa",
	"victor", "victoria", "vincent", "virginia", "walter", "warren", "wayne", "wendy",
	"wesley", "william", "wilson", "xavier", "yolanda", "zachary", "zoe", "aaron",
	"abby", "adrian", "aiden", "alan", "albert", "allison", "amber", "andre",
	"andrea", "ann", "annie", "april", "arthur", "becky", "bella", "ben",
	"betty", "bill", "billy", "bob", "bobby", "bonnie", "brad", "brenda",
	"brent", "brett", "brooke", "cameron", "candy", "carla", "carmen", "casey",
	"cassie", "chad", "charlie", "cheryl", "chloe", "cindy", "clara", "claude",
}

// 256 workplace verbs (32 rows x 8 columns = 256) - no duplicates
var defaultVerbs = []string{
	"helps", "assists", "supports", "guides", "mentors", "coaches", "trains", "teaches",
	"shows", "explains", "clarifies", "advises", "counsels", "directs", "leads", "manages",
	"shares", "gives", "sends", "passes", "hands", "offers", "provides", "delivers",
	"brings", "forwards", "transfers", "submits", "presents", "introduces", "recommends", "suggests",
	"tells", "informs", "notifies", "updates", "briefs", "reports", "announces", "confirms",
	"reminds", "alerts", "warns", "asks", "requests", "invites", "thanks", "greets",
	"joins", "meets", "calls", "emails", "messages", "contacts", "reaches", "connects",
	"schedules", "plans", "organizes", "arranges", "prepares", "coordinates", "hosts", "attends",
	"writes", "drafts", "creates", "designs", "develops", "builds", "makes", "produces",
	"edits", "revises", "reviews", "checks", "tests", "analyzes", "evaluates", "assesses",
	"fixes", "solves", "resolves", "handles", "addresses", "tackles", "processes", "completes",
	"finishes", "closes", "seals", "concludes", "finalizes", "achieves", "accomplishes", "fulfills",
	"learns", "studies", "researches", "explores", "discovers", "finds", "locates", "identifies",
	"understands", "grasps", "masters", "improves", "enhances", "upgrades", "advances", "progresses",
	"approves", "accepts", "agrees", "validates", "verifies", "certifies", "endorses", "authorizes",
	"praises", "commends", "recognizes", "rewards", "celebrates", "congratulates", "appreciates", "values",
	"opens", "starts", "begins", "launches", "initiates", "kicks", "triggers", "activates",
	"logs", "records", "documents", "files", "saves", "stores", "archives", "backups",
	"assigns", "delegates", "distributes", "allocates", "designates", "appoints", "nominates", "selects",
	"gathers", "collects", "compiles", "assembles", "combines", "merges", "integrates", "unifies",
	"covers", "backs", "defends", "protects", "secures", "safeguards", "shields", "guards",
	"funds", "sponsors", "finances", "budgets", "invests", "supplies", "equips", "furnishes",
	"moves", "shifts", "changes", "adjusts", "modifies", "adapts", "customizes", "tailors",
	"expands", "extends", "grows", "scales", "increases", "boosts", "raises", "elevates",
	"ensures", "guarantees", "promises", "commits", "pledges", "vows", "dedicates", "devotes",
	"maintains", "sustains", "preserves", "keeps", "retains", "holds", "carries", "operates",
	"tracks", "monitors", "watches", "observes", "follows", "traces", "audits", "inspects",
	"ranks", "rates", "scores", "grades", "measures", "quantifies", "calculates", "counts",
	"copies", "prints", "scans", "faxes", "mails", "ships", "packs", "bundles",
	"cleans", "tidies", "sorts", "orders", "labels", "marks", "stamps", "signs",
	"books", "reserves", "double-checks", "cancels", "reschedules", "postpones", "delays", "rushes",
	"fetches", "grabs", "picks", "drops", "lifts", "relocates", "places", "sets",
}

// 256 workplace objects (32 rows x 8 columns = 256)
var defaultObjects = []string{
	"reports", "documents", "files", "records", "forms", "papers", "sheets", "notes",
	"memos", "letters", "emails", "messages", "drafts", "copies", "prints", "scans",
	"slides", "decks", "presentations", "proposals", "pitches", "briefs", "summaries", "overviews",
	"outlines", "agendas", "minutes", "schedules", "calendars", "timelines", "roadmaps", "plans",
	"data", "numbers", "figures", "stats", "metrics", "charts", "graphs", "tables",
	"spreadsheets", "dashboards", "analytics", "insights", "findings", "results", "outcomes", "conclusions",
	"projects", "tasks", "assignments", "duties", "jobs", "work", "items", "tickets",
	"issues", "bugs", "features", "updates", "patches", "fixes", "changes", "revisions",
	"resources", "materials", "supplies", "tools", "equipment", "devices", "gadgets", "systems",
	"software", "apps", "programs", "platforms", "services", "solutions", "products", "offerings",
	"ideas", "concepts", "thoughts", "suggestions", "recommendations", "options", "alternatives", "choices",
	"strategies", "tactics", "approaches", "methods", "techniques", "practices", "procedures", "processes",
	"feedback", "comments", "reviews", "ratings", "scores", "grades", "marks", "points",
	"evaluations", "assessments", "appraisals", "critiques", "opinions", "views", "perspectives", "takes",
	"goals", "targets", "objectives", "aims", "purposes", "missions", "visions", "dreams",
	"milestones", "benchmarks", "standards", "criteria", "requirements", "specifications", "guidelines", "rules",
	"notices", "alerts", "reminders", "notifications", "warnings", "announcements", "bulletins", "circulars",
	"invitations", "requests", "inquiries", "questions", "answers", "responses", "replies", "acknowledgments",
	"meetings", "calls", "conferences", "sessions", "workshops", "seminars", "trainings", "webinars",
	"discussions", "conversations", "chats", "talks", "dialogues", "debates", "negotiations", "agreements",
	"budgets", "costs", "expenses", "invoices", "receipts", "bills", "payments", "refunds",
	"quotes", "estimates", "forecasts", "projections", "predictions", "trends", "patterns", "cycles",
	"contracts", "offers", "applications", "resumes", "portfolios", "references", "testimonials", "endorsements",
	"policies", "handbooks", "manuals", "guides", "tutorials", "instructions", "directions", "tips",
	"audits", "inspections", "checks", "tests", "trials", "experiments", "pilots", "proofs",
	"samples", "examples", "demos", "prototypes", "mockups", "wireframes", "designs", "blueprints",
	"achievements", "accomplishments", "successes", "wins", "victories", "awards", "prizes", "trophies",
	"certificates", "diplomas", "badges", "medals", "honors", "recognitions", "credits", "bonuses",
	"links", "urls", "sites", "pages", "posts", "articles", "blogs", "content",
	"photos", "images", "videos", "clips", "recordings", "podcasts", "streams", "broadcasts",
	"keys", "cards", "passes", "tags", "permits", "licenses", "credentials", "tokens",
	"snacks", "drinks", "lunches", "coffees", "treats", "gifts", "favors", "surprises",
}
