package sentencecipher

// Word lists with 256 words each - Theme: Office/Workplace stories
// Each word list has 256 entries (0-255) to encode 1 full byte per word

// 256 employee names (Shared across themes)
var defaultNames = []string{
	"adam", "alex", "alice", "amanda", "amy", "andrew", "angela", "anna",
	"anthony", "ashley", "austin", "barbara", "benjamin", "beth", "blake", "brandon",
	"brian", "brittany", "bruce", "carl", "carlos", "carol", "catherine", "charles",
	"charlotte", "chelsea", "chris", "christina", "claire", "cody", "colin", "connor",
	"cynthia", "daniel", "david", "deborah", "dennis", "diana", "diego", "dominic",
	"donna", "dorothy", "douglas", "dylan", "edward", "elena", "elizabeth", "emily",
	"emma", "eric", "ethan", "eva", "evan", "faith", "felix", "fiona",
	"francis", "frank", "gabriel", "gary", "george", "gloria", "grace", "gregory",
	"hannah", "harold", "harry", "heather", "helen", "henry", "holly", "howard",
	"ian", "irene", "iris", "isaac", "isabella", "ivan", "jack", "jacob",
	"james", "jane", "janet", "jasmine", "jason", "jean", "jeffrey", "jennifer",
	"jeremy", "jessica", "joan", "john", "jonathan", "jordan", "joseph", "joshua",
	"julia", "julie", "justin", "karen", "kate", "katherine", "keith", "kelly",
	"kenneth", "kevin", "kim", "kyle", "laura", "lauren", "lawrence", "leo",
	"leslie", "lily", "linda", "lisa", "logan", "louis", "lucas", "lucy",
	"luke", "lynn", "madison", "margaret", "maria", "marie", "mark", "martha",
	"martin", "mary", "mason", "matthew", "megan", "melissa", "michael", "michelle",
	"mike", "miranda", "molly", "monica", "nancy", "natalie", "nathan", "nicholas",
	"nicole", "nina", "noah", "nora", "oliver", "olivia", "oscar", "owen",
	"pamela", "patricia", "patrick", "paul", "paula", "peter", "philip", "rachel",
	"ralph", "raymond", "rebecca", "richard", "robert", "roger", "ronald", "rose",
	"ruby", "russell", "ruth", "ryan", "samantha", "samuel", "sandra", "sara",
	"sarah", "scott", "sean", "sharon", "shawn", "shirley", "simon", "sophia",
	"spencer", "stephanie", "stephen", "steven", "susan", "teresa", "thomas", "timothy",
	"tina", "todd", "tom", "tony", "tracy", "travis", "tyler", "vanessa",
	"victor", "victoria", "vincent", "virginia", "walter", "warren", "wayne", "wendy",
	"wesley", "william", "wilson", "xavier", "yolanda", "zachary", "zoe", "aaron",
	"abby", "adrian", "aiden", "alan", "albert", "allison", "amber", "andre",
	"andrea", "ann", "annie", "april", "arthur", "becky", "bella", "ben",
	"betty", "bill", "billy", "bob", "bobby", "bonnie", "brad", "brenda",
	"brent", "brett", "brooke", "cameron", "candy", "carla", "carmen", "casey",
	"cassie", "chad", "charlie", "cheryl", "chloe", "cindy", "clara", "claude",
}

// ==========================================
// THEME: BUSINESS / CORPORATE (Default)
// ==========================================

var businessSubjects = []string{
	"Project Update", "Meeting Notes", "Weekly Report", "Status Update",
	"Action Required", "Follow up", "Important Update", "Team Update",
	"Sync Up", "Discussion Points", "Next Steps", "Review Request",
	"Sprint Planning", "Budget Review", "Quarterly Goals", "Hiring Plan",
	"Client Feedback", "Marketing Strategy", "Sales Report", "Proposal Review",
}

// 256 workplace verbs (Business/General)
var defaultVerbs = []string{
	"helps", "assists", "supports", "guides", "mentors", "coaches", "trains", "teaches",
	"shows", "explains", "clarifies", "advises", "counsels", "directs", "leads", "manages",
	"shares", "gives", "sends", "passes", "hands", "offers", "provides", "delivers",
	"brings", "forwards", "transfers", "submits", "presents", "introduces", "recommends", "suggests",
	"tells", "informs", "notifies", "updates", "briefs", "reports", "announces", "confirms",
	"reminds", "alerts", "warns", "asks", "requests", "invites", "thanks", "greets",
	"joins", "meets", "calls", "emails", "messages", "contacts", "reaches", "connects",
	"schedules", "plans", "organizes", "arranges", "prepares", "coordinates", "hosts", "attends",
	"writes", "drafts", "creates", "designs", "develops", "builds", "makes", "produces",
	"edits", "revises", "reviews", "checks", "tests", "analyzes", "evaluates", "assesses",
	"fixes", "solves", "resolves", "handles", "addresses", "tackles", "processes", "completes",
	"finishes", "closes", "seals", "concludes", "finalizes", "achieves", "accomplishes", "fulfills",
	"learns", "studies", "researches", "explores", "discovers", "finds", "locates", "identifies",
	"understands", "grasps", "masters", "improves", "enhances", "upgrades", "advances", "progresses",
	"approves", "accepts", "agrees", "validates", "verifies", "certifies", "endorses", "authorizes",
	"praises", "commends", "recognizes", "rewards", "celebrates", "congratulates", "appreciates", "values",
	"opens", "starts", "begins", "launches", "initiates", "kicks", "triggers", "activates",
	"logs", "records", "documents", "files", "saves", "stores", "archives", "backups",
	"assigns", "delegates", "distributes", "allocates", "designates", "appoints", "nominates", "selects",
	"gathers", "collects", "compiles", "assembles", "combines", "merges", "integrates", "unifies",
	"covers", "backs", "defends", "protects", "secures", "safeguards", "shields", "guards",
	"funds", "sponsors", "finances", "budgets", "invests", "supplies", "equips", "furnishes",
	"moves", "shifts", "changes", "adjusts", "modifies", "adapts", "customizes", "tailors",
	"expands", "extends", "grows", "scales", "increases", "boosts", "raises", "elevates",
	"ensures", "guarantees", "promises", "commits", "pledges", "vows", "dedicates", "devotes",
	"maintains", "sustains", "preserves", "keeps", "retains", "holds", "carries", "operates",
	"tracks", "monitors", "watches", "observes", "follows", "traces", "audits", "inspects",
	"ranks", "rates", "scores", "grades", "measures", "quantifies", "calculates", "counts",
	"copies", "prints", "scans", "faxes", "mails", "ships", "packs", "bundles",
	"cleans", "tidies", "sorts", "orders", "labels", "marks", "stamps", "signs",
	"books", "reserves", "double-checks", "cancels", "reschedules", "postpones", "delays", "rushes",
	"fetches", "grabs", "picks", "drops", "lifts", "relocates", "places", "sets",
}

// 256 workplace objects (Business/General)
var defaultObjects = []string{
	"reports", "documents", "files", "records", "forms", "papers", "sheets", "notes",
	"memos", "letters", "emails", "messages", "drafts", "copies", "prints", "scans",
	"slides", "decks", "presentations", "proposals", "pitches", "briefs", "summaries", "overviews",
	"outlines", "agendas", "minutes", "schedules", "calendars", "timelines", "roadmaps", "plans",
	"data", "numbers", "figures", "stats", "metrics", "charts", "graphs", "tables",
	"spreadsheets", "dashboards", "analytics", "insights", "findings", "results", "outcomes", "conclusions",
	"projects", "tasks", "assignments", "duties", "jobs", "work", "items", "tickets",
	"issues", "bugs", "features", "updates", "patches", "fixes", "changes", "revisions",
	"resources", "materials", "supplies", "tools", "equipment", "devices", "gadgets", "systems",
	"software", "apps", "programs", "platforms", "services", "solutions", "products", "offerings",
	"ideas", "concepts", "thoughts", "suggestions", "recommendations", "options", "alternatives", "choices",
	"strategies", "tactics", "approaches", "methods", "techniques", "practices", "procedures", "processes",
	"feedback", "comments", "reviews", "ratings", "scores", "grades", "marks", "points",
	"evaluations", "assessments", "appraisals", "critiques", "opinions", "views", "perspectives", "takes",
	"goals", "targets", "objectives", "aims", "purposes", "missions", "visions", "dreams",
	"milestones", "benchmarks", "standards", "criteria", "requirements", "specifications", "guidelines", "rules",
	"notices", "alerts", "reminders", "notifications", "warnings", "announcements", "bulletins", "circulars",
	"invitations", "requests", "inquiries", "questions", "answers", "responses", "replies", "acknowledgments",
	"meetings", "calls", "conferences", "sessions", "workshops", "seminars", "trainings", "webinars",
	"discussions", "conversations", "chats", "talks", "dialogues", "debates", "negotiations", "agreements",
	"budgets", "costs", "expenses", "invoices", "receipts", "bills", "payments", "refunds",
	"quotes", "estimates", "forecasts", "projections", "predictions", "trends", "patterns", "cycles",
	"contracts", "offers", "applications", "resumes", "portfolios", "references", "testimonials", "endorsements",
	"policies", "handbooks", "manuals", "guides", "tutorials", "instructions", "directions", "tips",
	"audits", "inspections", "checks", "tests", "trials", "experiments", "pilots", "proofs",
	"samples", "examples", "demos", "prototypes", "mockups", "wireframes", "designs", "blueprints",
	"achievements", "accomplishments", "successes", "wins", "victories", "awards", "prizes", "trophies",
	"certificates", "diplomas", "badges", "medals", "honors", "recognitions", "credits", "bonuses",
	"links", "urls", "sites", "pages", "posts", "articles", "blogs", "content",
	"photos", "images", "videos", "clips", "recordings", "podcasts", "streams", "broadcasts",
	"keys", "cards", "passes", "tags", "permits", "licenses", "credentials", "tokens",
	"snacks", "drinks", "lunches", "coffees", "treats", "gifts", "favors", "surprises",
}

// ==========================================
// THEME: TECHNOLOGY / ENGINEERING
// ==========================================

var techSubjects = []string{
	"Server Outage", "Deployment Status", "API Updates", "Security Alert",
	"Code Review", "Database Migration", "System Maintenance", "Bug Bash",
	"Incident Report", "Release Notes", "Latency Issues", "Network Upgrade",
	"Cloud Infrastructure", "DevOps Sync", "Architecture Review", "Feature Flag",
}

// 256 Tech verbs
var techVerbs = []string{
	"codes", "programs", "compiles", "debugs", "executes", "runs", "builds", "deploys",
	"commits", "pushes", "pulls", "merges", "branches", "forks", "clones", "rebases",
	"fetches", "checkouts", "stashes", "reverts", "resets", "cherry-picks", "tags", "releases",
	"installs", "updates", "upgrades", "patches", "configures", "sets", "initializes", "boots",
	"restarts", "reboots", "shuts", "terminates", "kills", "stops", "halts", "suspends",
	"monitors", "logs", "tracks", "traces", "alerts", "notifies", "pings", "queries",
	"requests", "responses", "retrieves", "posts", "gets", "puts", "deletes", "corrects",
	"authenticates", "authorizes", "verifies", "validates", "encrypts", "decrypts", "hashes", "signs",
	"compresses", "zips", "archives", "extracts", "parses", "serializes", "encodes", "decodes",
	"renders", "paints", "draws", "displays", "shows", "hides", "toggles", "switches",
	"clicks", "taps", "scrolls", "swipes", "drags", "drops", "hovers", "focuses",
	"inputs", "types", "pastes", "copies", "cuts", "selects", "highlights", "edits",
	"saves", "loads", "reads", "writes", "opens", "closes", "imports", "exports",
	"uploads", "downloads", "syncs", "transfers", "streams", "buffers", "caches", "stores",
	"indexes", "searches", "filters", "sorts", "groups", "maps", "reduces", "iterates",
	"loops", "breaks", "continues", "returns", "throws", "catches", "tries", "awaits",
	"resolves", "rejects", "promises", "observes", "subscribes", "publishes", "emits", "broadcasts",
	"connects", "disconnects", "listens", "binds", "unbinds", "mounts", "unmounts", "routes",
	"navigates", "redirects", "forwards", "proxies", "tunnels", "bridges", "links", "chains",
	"tests", "mocks", "stubs", "spies", "asserts", "expects", "fails", "passes",
	"measures", "profiles", "benchmarks", "optimizes", "scales", "expands", "shrinks", "limits",
	"throttles", "blocks", "allows", "denies", "bans", "permits", "grants", "revokes",
	"assigns", "allocates", "frees", "collects", "cleans", "wipes", "erases", "formats",
	"partitions", "attaches", "ejects", "scans", "pairs", "charges", "powers", "drains",
	"computes", "calculates", "processes", "handles", "services", "providers", "consumes", "generates",
	"simulates", "emulates", "virtualizes", "containers", "dockers", "kubes", "orchestrates", "manages",
	"automates", "scripts", "commands", "controls", "rules", "governs", "directs", "leads",
	"analyzes", "inspects", "audits", "reviews", "checks", "examines", "probes", "assesses",
	"designs", "architects", "engineers", "develops", "implements", "integrates", "unifies", "combines",
	"refactors", "rewrites", "refines", "polishes", "improves", "fixes", "solves", "hacks",
	"tweaks", "tunes", "adjusts", "modifies", "changes", "transforms", "converts", "migrates",
	"deprecates", "removes", "scraps", "destroys", "discards", "purges", "prunes", "trims",
}

// 256 Tech objects
var techObjects = []string{
	"servers", "databases", "tables", "rows", "columns", "indexes", "views", "queries",
	"apis", "endpoints", "routes", "paths", "params", "headers", "bodies", "payloads",
	"tokens", "keys", "secrets", "passwords", "hashes", "salts", "ciphers", "certs",
	"logs", "metrics", "traces", "spans", "events", "signals", "alerts", "errors",
	"exceptions", "bugs", "issues", "tickets", "tasks", "stories", "epics", "sprints",
	"commits", "prs", "branches", "tags", "releases", "builds", "artifacts", "images",
	"containers", "pods", "nodes", "clusters", "services", "ingresses", "volumes", "networks",
	"firewalls", "rules", "policies", "roles", "groups", "users", "accounts", "profiles",
	"sessions", "cookies", "caches", "buffers", "queues", "topics", "channels", "streams",
	"sockets", "ports", "ips", "subnets", "dns", "records", "domains", "hosts",
	"files", "folders", "dirs", "locations", "links", "inodes", "blocks", "sectors",
	"disks", "drives", "ssds", "hdds", "raids", "partitions", "mounts", "swaps",
	"cpu", "ram", "gpu", "tpu", "cores", "threads", "processes", "daemons",
	"kernels", "drivers", "modules", "firmware", "bios", "bootloaders", "os", "distros",
	"shells", "terminals", "consoles", "scripts", "binaries", "libraries", "packages", "dependencies",
	"plugins", "imports", "exports", "classes", "objects", "functions", "methods", "variables",
	"constants", "types", "interfaces", "structs", "enums", "arrays", "lists", "maps",
	"sets", "trees", "graphs", "heaps", "stacks", "vectors", "matrices", "tensors",
	"strings", "integers", "floats", "booleans", "bytes", "bits", "chars", "runes",
	"pointers", "refs", "values", "scopes", "closures", "contexts", "promises", "futures",
	"fibers", "mutexes", "locks", "semaphores", "monitors", "conditions", "barriers", "latches",
	"frontend", "backend", "fullstack", "ui", "ux", "css", "html", "js",
	"react", "vue", "angular", "node", "deno", "bun", "go", "rust",
	"java", "python", "ruby", "php", "c", "cpp", "csharp", "swift",
	"kotlin", "scala", "clojure", "haskell", "elixir", "erlang", "lua", "perl",
	"sql", "nosql", "redis", "mongo", "postgres", "mysql", "sqlite", "oracle",
	"aws", "azure", "gcp", "cloud", "lambda", "s3", "ec2", "rds",
	"docker", "kubernetes", "helm", "terraform", "ansible", "jenkins", "gitlab", "github",
	"vscode", "vim", "emacs", "nano", "ide", "editor", "compiler", "debugger",
	"linter", "formatter", "parser", "lexer", "ast", "bytecode", "assembly", "machine",
	"laptop", "desktop", "monitor", "keyboard", "mouse", "trackpad", "webcam", "mic",
	"wifi", "bluetooth", "ethernet", "cable", "router", "switch", "modem", "gateway",
}

// Common components
var emailOpeners = []string{
	"Hi Team,",
	"Dear Colleagues,",
	"Hello everyone,",
	"Hi all,",
	"Good morning,",
	"Good afternoon,",
	"Team,",
	"Greetings,",
	"Hi there,",
	"All,",
}

// Connectors to chain sentences naturally
var sentenceConnectors = []string{
	"Please note that",
	"Additionally,",
	"Furthermore,",
	"Also,",
	"Moreover,",
	"In the meantime,",
	"Moving forward,",
	"As discussed,",
	"Just a reminder that",
	"For your information,",
	"However,",
	"Consequently,",
	"Therefore,",
	"In addition,",
	"Meanwhile,",
	"On another note,",
	"Interestingly,",
	"Remarkably,",
	"Specifically,",
	"Notably,",
	"To clarify,",
	"Currently,",
	"Recently,",
}

var emailClosers = []string{
	"Best regards,",
	"Kind regards,",
	"Sincerely,",
	"Thanks,",
	"Cheers,",
	"Best,",
	"Regards,",
	"Warm regards,",
	"Many thanks,",
	"Talk soon,",
}
